language: python
group: travis_latest
dist: xenial

sudo: false

matrix:
  include:

  - os: windows
    language: sh
    name: "Windows Python 2.7"
    before_install:
    - choco install python2
    - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
    - python -m pip install --upgrade pip
    - pip install codecov pytest-pep8 pytest-cov
    - pip install -e .

  - os: windows
    language: sh
    name: "Windows Python 3.7"
    before_install:
    - choco install python3
    - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
    - python -m pip install --upgrade pip
    - pip install codecov pytest-pep8 pytest-cov
    - pip install -e .

# install:
# - pip install --upgrade pip
# - if [[ $TRAVIS_PYTHON_VERSION == pypy3.5-6.0 ]]; then pip install "pytest-cov==2.6.0"; fi
# - pip install codecov pytest pytest-pep8 pytest-cov

script:
#  - py.test --pep8 --cov lib_registry
  - py.test --pep8 --cov lib_registry

# https://stackoverflow.com/questions/49254777/how-to-let-pytest-discover-and-run-doctests-in-installed-modules
# coverage run -p -m pytest {envsitepackagesdir}/my_package
# pytest --doctest-modules --doctest-continue-on-failure

after_success:
- pip install -e .
- coverage report
- codecov
